[[layer]]
name = "layer0"
keys = """
A B C D
Kc1 Kc2 Kc3 Kc4
"""
encoders = [["KC_VOLU", "KC_VOLD"]]

[[layer]]
name = "layer1"
keys = """
_ _ _ _
_ _ _ _
"""
encoders = [["KC_BRIU", "KC_BRID"]]

[[layer]]
name = "layer2"
keys = """
_ _ _ _
_ _ _ _
"""
encoders = [["KC_LEFT", "KC_RIGHT"]]

[[layer]]
name = "layer3"
keys = """
_ _ _ _
_ _ _ _
"""
encoders = [["_", "_"]]

[[layer]]
name = "layer4"
keys = """
_ _ _ _
_ _ _ _
"""
encoders = [["_", "_"]]

[[layer]]
name = "layer5"
keys = """
_ _ _ _
_ _ _ _
"""
encoders = [["_", "_"]]

[[layer]]
name = "layer6"
keys = """
_ _ _ _
_ _ _ _
"""
encoders = [["_", "_"]]

[[layer]]
name = "layer7"
keys = """
_ _ _ _
_ _ _ _
"""
encoders = [["_", "_"]]
